# Generated by Django 4.0.6 on 2025-11-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
    ]
